//Localhost

### Get all tasks

GET http://localhost:8080/tasks

### Create contact 
POST http://localhost:8080/tasks HTTP/1.1
content-type: application/json

{
    "taskName": "Find billy",
    "taskTime": 2,
    "completed": false,
    "createdAt": "2023-01-19T08:26:38.445Z"
}

### PUT contact 
PUT http://localhost:8080/tasks/63c8cc3d6aae4dfc48ad1533 HTTP/1.1
content-type: application/json

{
  "taskName": "Run around the gym",
  "taskTime": 1,
  "completed": false,
  "createdAt": "2023-01-19T08:28:00.204Z"
}
### DELETE contact 
DELETE http://localhost:8080/tasks/63c8cc3d6aae4dfc48ad1534 HTTP/1.1

//Production

### Get all tasks

GET http://localhost:8080/tasks

### Create contact 
POST http://localhost:8080/tasks HTTP/1.1
content-type: application/json

{
    "taskName": "Find billy",
    "taskTime": 2,
    "completed": false,
    "createdAt": "2023-01-19T08:26:38.445Z"
}

### PUT contact 
PUT http://localhost:8080/tasks/63c8cc3d6aae4dfc48ad1533 HTTP/1.1
content-type: application/json

{
  "taskName": "Run around the gym",
  "taskTime": 1,
  "completed": false,
  "createdAt": "2023-01-19T08:28:00.204Z"
}
### DELETE contact 
DELETE http://localhost:8080/tasks/63c8cc3d6aae4dfc48ad1534 HTTP/1.1