### Create contact 
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Iris",
    "lastName":"Toody", 
    "email":"iris@bestmail.com", 
    "favouriteColor":"Orange", 
    "birthday":"01/04/06"
}

### PUT contact 
PUT http://localhost:3000/contacts/63c008d5bf6ee14b0614013a HTTP/1.1
content-type: application/json

{
    "firstName":"Iris", 
    "lastName":"Toody",
    "email":"iris@bestmail.com", 
    "favouriteColor":"Green", 
    "birthday":"02/12/06"
}
### DELETE contact 
DELETE http://localhost:3000/contacts/63c008d5bf6ee14b0614013a HTTP/1.1

### Create contact 
POST https://lesson1-coyc.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Iris",
    "lastName":"Toody", 
    "email":"iris@bestmail.com", 
    "favouriteColor":"Orange", 
    "birthday":"01/04/06"
}

### PUT contact 
PUT https://lesson1-coyc.onrender.com/contacts/63c016b89bd4c97db442cb0b HTTP/1.1
content-type: application/json

{
    "firstName":"Iris", 
    "lastName":"Toody",
    "email":"iris@bestmail.com", 
    "favouriteColor":"Green", 
    "birthday":"02/12/06"
}

### DELETE contact 
DELETE https://lesson1-coyc.onrender.com/contacts/63c016b89bd4c97db442cb0b HTTP/1.1